#!/usr/bin/env python3
"""Generate a Codex runtime from the Claude-side agent-system sources.

The editable source of truth is CLAUDE.md plus .claude/**. AGENTS.md and
.agents/** and managed .codex/** files are generated outputs and must not be edited directly.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path


VERSION = 1
MANIFEST_REL = Path(".codex/.sync/claude-to-codex.json")
LOCK_REL = Path(".codex/.sync/claude-to-codex.lock")
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}[a-z0-9]$|^[a-z0-9]$")
SECRET_PATTERNS = (
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"(?<![A-Za-z0-9])gh[pousr]_[A-Za-z0-9_]{20,}"),
    re.compile(r"(?<![A-Za-z0-9])sk-[A-Za-z0-9_-]{20,}"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"\b[0-9]{8,10}:[A-Za-z0-9_-]{30,}\b"),
)
WRITE_TOOLS = {"edit", "multiedit", "notebookedit", "write"}
WRITE_BY_ROLE = {"watchdog"}
GENERATED_MARKER = "Generated by sync_to_codex.py. Do not edit directly."


class SyncError(Exception):
    """Base error for safe, user-actionable sync failures."""

    exit_code = 2


class ConflictError(SyncError):
    """A generated target was edited independently."""

    exit_code = 3


@dataclass(frozen=True)
class Output:
    source: str
    target: Path
    adapter: str
    content: str | bytes


@dataclass(frozen=True)
class PlannedAction:
    action: str
    output: Output | None
    target: Path
    reason: str = ""


def content_bytes(content: str | bytes) -> bytes:
    return content.encode("utf-8") if isinstance(content, str) else content


def digest(content: str | bytes) -> str:
    return hashlib.sha256(content_bytes(content)).hexdigest()


def validate_slug(value: str, label: str) -> None:
    if not SLUG_RE.fullmatch(value):
        raise SyncError(f"invalid {label} slug: {value!r}")


def relative_inside(path: Path, root: Path) -> Path:
    try:
        return path.resolve().relative_to(root.resolve())
    except ValueError as exc:
        raise SyncError(f"path escapes project root: {path}") from exc


def reject_symlink(path: Path, root: Path) -> None:
    relative = relative_inside(path, root)
    current = root.resolve()
    for part in relative.parts:
        current /= part
        if current.is_symlink():
            raise SyncError(f"symlink source rejected: {path}")


def contains_secret(text: str) -> bool:
    return any(pattern.search(text) for pattern in SECRET_PATTERNS)


def read_source_bytes(path: Path, root: Path) -> bytes:
    reject_symlink(path, root)
    raw = path.read_bytes()
    if contains_secret(raw.decode("utf-8", errors="ignore")):
        raise SyncError(f"secret-looking content rejected: {path}")
    return raw


def read_source(path: Path, root: Path) -> str:
    try:
        text = read_source_bytes(path, root).decode("utf-8")
    except UnicodeDecodeError as exc:
        raise SyncError(f"non-UTF-8 source rejected: {path}") from exc
    if contains_secret(text):
        raise SyncError(f"secret-looking content rejected: {path}")
    return text


def split_frontmatter(text: str) -> tuple[dict[str, str | list[str]], str]:
    """Parse the small YAML subset used by Claude agent and skill files."""
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return {}, text
    end = next((index for index, line in enumerate(lines[1:], 1) if line.strip() == "---"), None)
    if end is None:
        raise SyncError("unterminated YAML frontmatter")

    raw = [line.rstrip("\r\n") for line in lines[1:end]]
    metadata: dict[str, str | list[str]] = {}
    index = 0
    while index < len(raw):
        line = raw[index]
        if not line.strip():
            index += 1
            continue
        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if not match:
            index += 1
            continue
        key, value = match.group(1), match.group(2).strip()
        if value in {"|", ">"}:
            index += 1
            block: list[str] = []
            while index < len(raw) and (not raw[index].strip() or raw[index][0].isspace()):
                block.append(raw[index].strip())
                index += 1
            metadata[key] = "\n".join(block).strip()
            continue
        if not value:
            index += 1
            values: list[str] = []
            while index < len(raw):
                item = re.match(r"^\s+-\s+(.+)$", raw[index])
                if not item:
                    break
                values.append(item.group(1).strip().strip("'\""))
                index += 1
            metadata[key] = values
            continue
        metadata[key] = value.strip("'\"")
        index += 1
    return metadata, "".join(lines[end + 1 :]).lstrip("\r\n")


def metadata_list(value: str | list[str] | None) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [item.strip() for item in value if item.strip()]
    stripped = value.strip()
    if stripped.startswith("[") and stripped.endswith("]"):
        stripped = stripped[1:-1]
    return [item.strip().strip("'\"") for item in stripped.split(",") if item.strip()]


def markdown_header(source: str) -> str:
    return f"<!-- {GENERATED_MARKER} Source: {source}. -->\n"


def toml_string(value: str) -> str:
    """Return a single-line TOML basic string and avoid multiline injection."""
    replacements = {
        "\\": "\\\\",
        '"': '\\"',
        "\b": "\\b",
        "\t": "\\t",
        "\n": "\\n",
        "\f": "\\f",
        "\r": "\\r",
    }
    encoded = "".join(replacements.get(char, char) for char in value)
    return f'"{encoded}"'


def serialize_agent(fields: dict[str, str]) -> str:
    required = {"name", "description", "developer_instructions", "sandbox_mode"}
    allowed = required | {"model_reasoning_effort"}
    if not required.issubset(fields) or set(fields) - allowed:
        raise SyncError(f"unexpected Codex agent fields: {sorted(set(fields) - allowed)}")
    content = "\n".join(f"{key} = {toml_string(value)}" for key, value in fields.items()) + "\n"
    parsed = tomllib.loads(content)
    if parsed != fields:
        raise SyncError("Codex agent TOML failed round-trip validation")
    return f"# {GENERATED_MARKER}\n{content}"


RUNTIME_REPLACEMENTS = (
    ('TeamCreate(team_name="skill-test-{skill-name}")', 'create a supervised `skill-test-{skill-name}` subagent group with `spawn_agent`'),
    ('Task(subagent_type="meta-reviewer", prompt="Analyze the session...", model="opus")', 'spawn_agent(task_name="meta-reviewer", message="Analyze the session...")'),
    ("ScheduleWakeup(delaySeconds = clamp(reset_at - now, 60, 3600))", "a supported runtime automation scheduled for min(reset_at - now, 1 hour)"),
    ("ScheduleWakeup(reset_at + 60s)", "a supported runtime automation scheduled for reset_at + 60s"),
    ("`ScheduleWakeup`", "a supported runtime automation"),
    ("`Monitor` stream", "`wait_agent` supervision"),
    ("use `Agent`", "use `spawn_agent`"),
    ("TeamCreate", "spawn_agent orchestration"),
    ("TaskStop", "interrupt_agent"),
    ("SendMessage", "send_message"),
    ("TaskList", "list_agents"),
    ("ScheduleWakeup", "runtime automation"),
    ("AskUserQuestion", "a concise question in chat"),
    ("TodoWrite", "update_plan"),
    ("run_in_background: true", "parallel spawn_agent calls"),
    ("subagent_type", "task_name"),
    ("Task tool", "spawn_agent tool"),
    ("Agent tool", "spawn_agent tool"),
    ("Skill tool", "matching Codex skill"),
    ("Agent({task_name, prompt})", "spawn_agent({task_name, message})"),
    ("Agent(...)", "spawn_agent(...)"),
    ("Task(", "spawn_agent("),
    ("Skill(skill: ", "Use Codex skill: "),
    ("/loop 10m /sweep-watchdog", "recurring 10-minute sweep-watchdog monitoring"),
)


def adapt_runtime_terms(text: str) -> str:
    """Adapt operational primitives while preserving .claude as source paths."""
    for old, new in RUNTIME_REPLACEMENTS:
        text = text.replace(old, new)
    text = re.sub(r"\bAgent\(\{subagent_type,\s*prompt\}\)", "spawn_agent({task_name, message})", text)
    text = re.sub(r"\bSkill\(([^\n)]*)\)", r"Load Codex skill: \1", text)
    return text


def codex_runtime_note() -> str:
    return (
        "## Codex runtime adapter\n\n"
        "- Use Codex collaboration tools (`spawn_agent`, `send_message`, `wait_agent`, "
        "`list_agents`, `interrupt_agent`) when they are available.\n"
        "- Codex has no Claude Agent Team shared runtime. The parent agent owns wave state, "
        "checkpoints, aggregation, and conflict resolution.\n"
        "- Keep `.claude/**` as the editable source of truth. Read generated `.agents/**` and `.codex/**` "
        "for runtime discovery, but never edit it directly.\n"
        "- After changing `CLAUDE.md` or `.claude/**`, run "
        "`python .claude/shared/scripts/sync_to_codex.py --project . --apply --prune`.\n"
    )


def render_agents_md(project: Path) -> Output:
    source = project / "CLAUDE.md"
    text = read_source(source, project)
    text = text.replace(
        "Slash command (e.g. `/interview`, `/tech-plan`, `/do-task`) → load `.claude/commands/{name}.md`; the command spec decides what skill to spawn.",
        "Slash-command intent (e.g. `/interview`, `/tech-plan`, `/do-task`) → use `.agents/skills/source-command-{name}/SKILL.md`; that adapter selects the methodology skill.",
    )
    text = text.replace(
        "Dev-related message (feature request, bug report, code question, refactor) → load `.claude/team-lead.md` (root); team-lead applies its own classifier to pick the pipeline.",
        "Dev-related message (feature request, bug report, code question, refactor) → use the `team-lead` skill from `.agents/skills/team-lead/SKILL.md`.",
    )
    text = text.replace("Team Lead protocol → `.claude/team-lead.md`", "Team Lead runtime → `.agents/skills/team-lead/SKILL.md`")
    text = text.replace("Agent specs → `.claude/agents/{name}.md`", "Native Codex agents → `.codex/agents/{name}.toml`")
    text = text.replace("Skills (methodology, code-writing, reviews, etc.) → `.claude/skills/{name}/SKILL.md`", "Codex skill runtime → `.agents/skills/{name}/SKILL.md`; editable source → `.claude/skills/{name}/SKILL.md`")
    preamble = (
        f"<!-- {GENERATED_MARKER} Source: CLAUDE.md. -->\n"
        "# Dual-runtime policy\n\n"
        "`CLAUDE.md` and `.claude/**` are the editable source of truth. `AGENTS.md`, `.agents/**`, "
        "and managed `.codex/**` files are generated Codex runtime files. Never edit generated files directly. "
        "When instructions, agents, commands, skills, or Project Knowledge change, edit the "
        "Claude-side source and regenerate Codex. Commit source and generated changes together.\n\n"
        "Codex may use independent and parallel subagents, but the parent agent must coordinate "
        "them explicitly; do not assume Claude Agent Team shared state exists.\n\n"
    )
    content = preamble + adapt_runtime_terms(text)
    return Output("CLAUDE.md", project / "AGENTS.md", "project-instructions", content)


def render_team_lead(project: Path) -> Output:
    source = project / ".claude/team-lead.md"
    body = adapt_runtime_terms(read_source(source, project))
    content = (
        "---\n"
        "name: team-lead\n"
        "description: Orchestrate development requests, classify scope, plan work, delegate to specialists, supervise reviews, and aggregate results. Use for feature requests, bugs, refactors, implementation, and spec-driven delivery.\n"
        "---\n\n"
        f"{markdown_header('.claude/team-lead.md')}"
        f"{codex_runtime_note()}\n\n{body}"
    )
    return Output(str(source.relative_to(project)), project / ".agents/skills/team-lead/SKILL.md", "team-lead", content)


def render_consultant_base(project: Path) -> Output:
    source = project / ".claude/consultant-base.md"
    content = markdown_header(str(source.relative_to(project))) + adapt_runtime_terms(read_source(source, project))
    return Output(str(source.relative_to(project)), project / ".codex/consultant-base.md", "shared-agent-contract", content)


def render_skill_outputs(project: Path) -> list[Output]:
    source_root = project / ".claude/skills"
    outputs: list[Output] = []
    if not source_root.is_dir():
        return outputs
    seen_names: set[str] = set()
    for skill_dir in sorted(path for path in source_root.iterdir() if path.is_dir()):
        validate_slug(skill_dir.name, "skill directory")
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.is_file():
            raise SyncError(f"skill missing SKILL.md: {skill_dir}")
        metadata, _ = split_frontmatter(read_source(skill_file, project))
        name = metadata.get("name")
        description = metadata.get("description")
        if not isinstance(name, str) or not isinstance(description, str) or not name or not description:
            raise SyncError(f"skill frontmatter requires name and description: {skill_file}")
        validate_slug(name, "skill name")
        if name != skill_dir.name:
            raise SyncError(f"skill name must match directory: {skill_file}")
        if name in seen_names:
            raise SyncError(f"duplicate skill name: {name}")
        seen_names.add(name)

        for source in sorted(path for path in skill_dir.rglob("*") if path.is_file()):
            if "__pycache__" in source.parts or source.suffix in {".pyc", ".pyo"}:
                continue
            relative = source.relative_to(source_root)
            raw = read_source_bytes(source, project)
            try:
                source_text = raw.decode("utf-8")
            except UnicodeDecodeError:
                outputs.append(Output(str(source.relative_to(project)), project / ".agents/skills" / relative, "skill-asset", raw))
                continue
            if contains_secret(source_text):
                raise SyncError(f"secret-looking content rejected: {source}")
            text = adapt_runtime_terms(source_text)
            if source.name == "SKILL.md":
                metadata, body = split_frontmatter(text)
                frontmatter = (
                    "---\n"
                    f"name: {metadata['name']}\n"
                    f"description: |\n  {str(metadata['description']).replace(chr(10), chr(10) + '  ')}\n"
                    "---\n\n"
                )
                text = frontmatter + markdown_header(str(source.relative_to(project))) + codex_runtime_note() + "\n\n" + body
            elif source.suffix == ".md":
                text = markdown_header(str(source.relative_to(project))) + text
            outputs.append(Output(str(source.relative_to(project)), project / ".agents/skills" / relative, "skill", text))
    return outputs


def render_agent_outputs(project: Path) -> list[Output]:
    source_root = project / ".claude/agents"
    outputs: list[Output] = []
    if not source_root.is_dir():
        return outputs
    for source in sorted(source_root.glob("*.md")):
        metadata, body = split_frontmatter(read_source(source, project))
        name, description = metadata.get("name"), metadata.get("description")
        if not isinstance(name, str) or not isinstance(description, str) or not name or not description:
            raise SyncError(f"agent frontmatter requires name and description: {source}")
        validate_slug(name, "agent name")
        tools = {tool.lower() for tool in metadata_list(metadata.get("allowed-tools"))}
        sandbox_mode = "workspace-write" if tools & WRITE_TOOLS or name in WRITE_BY_ROLE else "read-only"
        instructions = codex_runtime_note() + "\n\n" + adapt_runtime_terms(body).strip()
        skills = metadata_list(metadata.get("skills"))
        if skills:
            pointers = "\n".join(
                f"- Load `.agents/skills/{skill}/SKILL.md` before starting." for skill in skills
            )
            instructions += f"\n\n## Required methodology\n\n{pointers}"
        if "consultant-base.md" in instructions:
            instructions += "\n\nRead `.codex/consultant-base.md` before analysis and follow its complete base contract."
        fields = {
            "name": name,
            "description": adapt_runtime_terms(description),
            "developer_instructions": instructions,
            "sandbox_mode": sandbox_mode,
        }
        effort_map = {"opus": "high", "sonnet": "medium", "haiku": "low"}
        model_hint = metadata.get("model")
        if isinstance(model_hint, str) and model_hint in effort_map:
            fields["model_reasoning_effort"] = effort_map[model_hint]
        outputs.append(
            Output(
                str(source.relative_to(project)),
                project / ".codex/agents" / f"{name}.toml",
                "agent",
                serialize_agent(fields),
            )
        )
    return outputs


def render_command_outputs(project: Path) -> list[Output]:
    source_root = project / ".claude/commands"
    outputs: list[Output] = []
    if not source_root.is_dir():
        return outputs
    for source in sorted(source_root.glob("*.md")):
        validate_slug(source.stem, "command")
        metadata, body = split_frontmatter(read_source(source, project))
        raw_description = metadata.get("description")
        description = str(raw_description).splitlines()[0].strip() if raw_description else f"Run the {source.stem} workflow."
        slug = f"source-command-{source.stem}"
        validate_slug(slug, "command skill")
        content = (
            "---\n"
            f"name: {slug}\n"
            "description: |\n"
            f"  Codex adapter for the Claude `/{source.stem}` command. {description}\n"
            "  Use when the user invokes that command or asks for the equivalent workflow.\n"
            "---\n\n"
            f"{markdown_header(str(source.relative_to(project)))}"
            f"{codex_runtime_note()}\n\n"
            f"# Command workflow: /{source.stem}\n\n"
            "Treat Claude-only command syntax as workflow intent and use the available Codex tools.\n\n"
            f"{adapt_runtime_terms(body)}"
        )
        outputs.append(
            Output(
                str(source.relative_to(project)),
                project / ".agents/skills" / slug / "SKILL.md",
                "command-skill",
                content,
            )
        )
    return outputs


def render_codex_config(project: Path) -> Output:
    content = (
        f"# {GENERATED_MARKER}\n"
        "# The root orchestrator owns review waves and shared state.\n"
        "[agents]\n"
        "max_threads = 6\n"
        "max_depth = 1\n"
    )
    tomllib.loads(content)
    return Output(".claude/team-lead.md", project / ".codex/config.toml", "codex-config", content)


def adapt_hook_text(text: str, name: str) -> str:
    text = adapt_runtime_terms(text)
    if name == "SessionStart.sh":
        text = text.replace(
            'echo "/do-all-tasks $FEATURE"',
            'echo "Resume feature execution for $FEATURE. Load .agents/skills/source-command-do-all-tasks/SKILL.md and continue from checkpoint.yml."',
        )
    if name == "post-compact-restore.sh":
        start = text.find("# Check if this session is the team lead.")
        end = text.find("# Output recovery context", start)
        if start != -1 and end != -1:
            text = text[:start] + (
                "# Codex has no Claude Agent Team config file. The root thread owns\n"
                "# checkpoint recovery, so resume from the filesystem artifact directly.\n\n"
            ) + text[end:]
        text = text.replace(
            'echo "Load skill: feature-execution"',
            'echo "Load skill: feature-execution from .agents/skills/feature-execution/SKILL.md"',
        )
    return text


def render_hook_outputs(project: Path) -> list[Output]:
    source_root = project / ".claude/hooks"
    if not source_root.is_dir():
        return []
    outputs: list[Output] = []
    for name in ("SessionStart.sh", "post-compact-restore.sh"):
        source = source_root / name
        if source.is_file():
            body = adapt_hook_text(read_source(source, project), name)
            outputs.append(Output(str(source.relative_to(project)), project / ".codex/hooks" / name, "hook", body))

    command = 'bash "$(git rev-parse --show-toplevel)/.codex/hooks/{name}"'
    hooks = {
        "hooks": {
            "SessionStart": [
                {
                    "matcher": "startup|resume|clear",
                    "hooks": [{
                        "type": "command",
                        "command": command.format(name="SessionStart.sh"),
                        "command_windows": command.format(name="SessionStart.sh"),
                        "statusMessage": "Checking resumable feature work",
                    }],
                },
                {
                    "matcher": "compact",
                    "hooks": [{
                        "type": "command",
                        "command": command.format(name="post-compact-restore.sh"),
                        "command_windows": command.format(name="post-compact-restore.sh"),
                        "statusMessage": "Restoring feature checkpoint",
                    }],
                },
            ]
        }
    }
    content = json.dumps(hooks, ensure_ascii=False, indent=2) + "\n"
    outputs.append(Output(".claude/hooks", project / ".codex/hooks.json", "hooks-config", content))
    return outputs


def build_outputs(project: Path) -> list[Output]:
    required = [project / "CLAUDE.md", project / ".claude/team-lead.md", project / ".claude/consultant-base.md"]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise SyncError(f"required sources missing: {', '.join(missing)}")
    outputs = [render_agents_md(project), render_team_lead(project), render_consultant_base(project), render_codex_config(project)]
    outputs.extend(render_skill_outputs(project))
    outputs.extend(render_agent_outputs(project))
    outputs.extend(render_command_outputs(project))
    outputs.extend(render_hook_outputs(project))
    targets = [str(output.target.relative_to(project)) for output in outputs]
    if len(targets) != len(set(targets)):
        raise SyncError("two sources generate the same Codex target")
    for output in outputs:
        relative = relative_inside(output.target, project)
        if relative != Path("AGENTS.md") and relative.parts[:1] not in ((".codex",), (".agents",)):
            raise SyncError(f"generated target outside allowlist: {output.target}")
        if isinstance(output.content, str) and contains_secret(output.content):
            raise SyncError(f"secret-looking generated content rejected: {output.target}")
    return outputs


def load_manifest(project: Path) -> dict:
    path = project / MANIFEST_REL
    if not path.exists():
        return {"version": VERSION, "outputs": {}}
    reject_symlink(path, project)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise SyncError(f"invalid sync manifest: {path}") from exc
    if not isinstance(data.get("outputs", {}), dict):
        raise SyncError(f"invalid outputs map in sync manifest: {path}")
    return data


def plan_actions(project: Path, outputs: list[Output], prune: bool, force: bool) -> list[PlannedAction]:
    previous = load_manifest(project).get("outputs", {})
    desired = {str(output.target.relative_to(project)).replace("\\", "/"): output for output in outputs}
    actions: list[PlannedAction] = []
    for relative, output in sorted(desired.items()):
        target = output.target
        if not target.exists():
            actions.append(PlannedAction("create", output, target))
            continue
        reject_symlink(target, project)
        current = target.read_bytes()
        if current == content_bytes(output.content):
            actions.append(PlannedAction("unchanged", output, target))
            continue
        previous_hash = previous.get(relative, {}).get("output_sha256")
        if not force and (not previous_hash or digest(current) != previous_hash):
            actions.append(PlannedAction("conflict", output, target, "generated target was edited or is unmanaged"))
        else:
            actions.append(PlannedAction("update", output, target))

    for relative, entry in sorted(previous.items()):
        if relative in desired:
            continue
        target = project / Path(relative)
        if not target.exists():
            continue
        reject_symlink(target, project)
        current_hash = digest(target.read_bytes())
        if current_hash != entry.get("output_sha256"):
            actions.append(PlannedAction("conflict", None, target, "stale generated target was edited"))
        elif prune:
            actions.append(PlannedAction("delete", None, target, "source removed"))
        else:
            actions.append(PlannedAction("stale", None, target, "source removed; rerun with --prune"))
    return actions


def atomic_write(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(content_bytes(content))
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
    finally:
        temporary = Path(temporary_name)
        if temporary.exists():
            temporary.unlink()


def process_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def stale_lock(lock: Path) -> bool:
    try:
        raw = lock.read_text(encoding="utf-8").strip()
        pid = int(raw)
    except (OSError, UnicodeDecodeError, ValueError):
        return True
    return pid == os.getpid() or not process_alive(pid)


def acquire_lock(project: Path) -> Path:
    lock = project / LOCK_REL
    lock.parent.mkdir(parents=True, exist_ok=True)
    reject_symlink(lock.parent, project)
    for attempt in range(2):
        try:
            descriptor = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            break
        except FileExistsError as exc:
            if attempt == 0 and stale_lock(lock):
                lock.unlink()
                continue
            raise SyncError(f"another Codex sync may be running: {lock}") from exc
    else:  # pragma: no cover - loop either breaks or raises
        raise SyncError(f"could not acquire Codex sync lock: {lock}")
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(str(os.getpid()))
    return lock


def write_manifest(project: Path, outputs: list[Output]) -> None:
    entries = {}
    for output in sorted(outputs, key=lambda item: str(item.target)):
        relative = str(output.target.relative_to(project)).replace("\\", "/")
        source_path = project / output.source
        source_content = read_source_bytes(source_path, project) if source_path.is_file() else b""
        entries[relative] = {
            "source": output.source.replace("\\", "/"),
            "adapter": output.adapter,
            "source_sha256": digest(source_content),
            "output_sha256": digest(output.content),
        }
    manifest = {"version": VERSION, "generator": ".claude/shared/scripts/sync_to_codex.py", "outputs": entries}
    atomic_write(project / MANIFEST_REL, json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n")


def apply_actions(project: Path, outputs: list[Output], actions: list[PlannedAction]) -> None:
    conflicts = [action for action in actions if action.action == "conflict"]
    if conflicts:
        paths = ", ".join(str(action.target.relative_to(project)) for action in conflicts)
        raise ConflictError(f"refusing to overwrite independently edited targets: {paths}")
    lock = acquire_lock(project)
    try:
        for action in actions:
            if action.action in {"create", "update"}:
                assert action.output is not None
                atomic_write(action.target, action.output.content)
            elif action.action == "delete":
                action.target.unlink()
                parent = action.target.parent
                while parent != project and parent != project / ".codex" and parent.exists():
                    try:
                        parent.rmdir()
                    except OSError:
                        break
                    parent = parent.parent
        write_manifest(project, outputs)
    finally:
        lock.unlink(missing_ok=True)


def report(project: Path, actions: list[PlannedAction]) -> None:
    counts: dict[str, int] = {}
    for action in actions:
        counts[action.action] = counts.get(action.action, 0) + 1
    summary = ", ".join(f"{key}={counts[key]}" for key in sorted(counts))
    print(f"sync-to-codex: {summary or 'no outputs'}")
    for action in actions:
        if action.action not in {"unchanged"}:
            suffix = f" ({action.reason})" if action.reason else ""
            print(f"  {action.action}: {action.target.relative_to(project)}{suffix}")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--apply", action="store_true", help="Write generated runtime files.")
    mode.add_argument("--check", action="store_true", help="Exit 1 when generated runtime has drift.")
    parser.add_argument("--project", type=Path, default=Path.cwd(), help="Project root. Default: current directory.")
    parser.add_argument("--prune", action="store_true", help="Delete stale manifest-owned outputs.")
    parser.add_argument("--force", action="store_true", help="Overwrite unmanaged or independently edited generated targets.")
    parser.add_argument("--quiet", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    project = args.project.expanduser().resolve()
    if not project.is_dir():
        print(f"error: project root not found: {project}", file=sys.stderr)
        return 2
    try:
        outputs = build_outputs(project)
        actions = plan_actions(project, outputs, prune=args.prune, force=args.force)
        if not args.quiet:
            report(project, actions)
        if args.apply:
            apply_actions(project, outputs, actions)
            if not args.quiet:
                print("Codex runtime generated successfully.")
            return 0
        drift = any(action.action not in {"unchanged"} for action in actions)
        if args.check and drift:
            return 1
        return 0
    except SyncError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return exc.exit_code


if __name__ == "__main__":
    raise SystemExit(main())

