#!/usr/bin/env python3
"""Generate a Codex runtime from the Claude-side agent-system sources.

The editable source of truth is CLAUDE.md plus .claude/**. AGENTS.md and
.agents/** and managed .codex/** files are generated outputs and must not be edited directly.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path, PurePosixPath, PureWindowsPath


# Shipped-runtime consumer contract (architect F8; extended by architect
# F-01, review round 2): sync_to_os.py dynamically imports this module from
# the sanitized OS-side target checkout and calls exactly these names — see
# `_CODEX_GENERATOR_CONTRACT` and `_load_codex_generator_module()` /
# `_validate_codex_generator_contract()` in
# `.claude/shared/scripts/sync_to_os.py`, which validate a loaded module
# against this same set at import time and refuse (RuntimeError) if any are
# missing. `Output` and `PlannedAction` are included because the consumer
# also depends on their attribute SHAPE (`output.target`/`output.content`,
# `action.action`/`action.target`), not just their existence — renaming or
# reshaping any of these names is a breaking change for sync_to_os.py, which
# is why `CONTRACT_VERSION` below exists: bump it whenever this surface
# changes in a breaking way, so a version-skewed pairing refuses loudly
# instead of failing deep inside generation. `main` is the CLI entry point
# used by `python sync_to_codex.py --apply/--check/--prune`. Declaring this
# here (rather than only on the consumer side) is the provider-side half of
# the contract; provider-side guard tests live in tests/test_sync_to_codex.py
# (SyncToCodexTests.test_all_declares_consumer_required_names and friends).
__all__ = [
    "build_outputs",
    "plan_actions",
    "apply_actions",
    "MANIFEST_REL",
    "Output",
    "PlannedAction",
    "main",
    "CONTRACT_VERSION",
]

# Bump on any BREAKING change to the __all__ surface above (new required
# field, removed/renamed name, changed semantics of an existing field the
# consumer reads). sync_to_os.py refuses to generate if this doesn't match
# its own _EXPECTED_CODEX_CONTRACT_VERSION (architect F-01).
CONTRACT_VERSION = 1

# `.codex/.sync/claude-to-codex.json` MANIFEST schema version (checked by
# load_manifest() below) — unrelated to CONTRACT_VERSION above, which
# versions the build_outputs/plan_actions/apply_actions API surface
# sync_to_os.py depends on. Bump this one when the on-disk manifest JSON
# shape itself changes; bump CONTRACT_VERSION when the Python API does.
VERSION = 1
MANIFEST_GENERATOR = ".claude/shared/scripts/sync_to_codex.py"
MANIFEST_REL = Path(".codex/.sync/claude-to-codex.json")
LOCK_REL = Path(".codex/.sync/claude-to-codex.lock")
POLICY_REL = Path(".claude/codex/agent-profiles.toml")
CONTRACT_REL = Path(".claude/codex/runtime-contract.md")
PRIVILEGED_ROLES_REL = Path(".claude/codex/privileged-roles.md")
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}[a-z0-9]$|^[a-z0-9]$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
SECRET_PATTERNS = (
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"(?<![A-Za-z0-9])gh[pousr]_[A-Za-z0-9_]{20,}"),
    re.compile(r"(?<![A-Za-z0-9])sk-[A-Za-z0-9_-]{20,}"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"\b[0-9]{8,10}:[A-Za-z0-9_-]{30,}\b"),
    # Tier 5 (codex-dual-runtime, work/codex-dual-runtime/decisions.md
    # "Publication frozen until Z.AI key rotation"): Z.AI / GLM API key
    # shape — a 32-char hex id, a literal dot, a 16-char mixed-case
    # alphanumeric secret. Mirrors the FROZEN_FORBIDDEN entry in
    # sync_tool/config.py (both live independently — the contains_secret()
    # guard right here, inside build_outputs(), is a first-pass check baked
    # into generation itself, ahead of the sync_to_os.py authoritative
    # post-generation re-scan). re.IGNORECASE is explicit here because —
    # unlike the other entries in this tuple, which are case-sensitive —
    # a hex id could plausibly be hand-typed in uppercase.
    re.compile(r"\b[0-9a-f]{32}\.[A-Za-z0-9]{16}\b", re.IGNORECASE),
)
WRITE_TOOLS = {"edit", "multiedit", "notebookedit", "write"}
GENERATED_MARKER = "Generated by sync_to_codex.py. Do not edit directly."
# Skills whose own body instructs the reader to spawn/schedule other agents
# (native parent-orchestrator primitives). Every other skill is a non-spawning
# leaf. Populated by manual inspection of each .claude/skills/*/SKILL.md body
# for native spawn/schedule instructions — see review round 2 (C1 fix).
#
# NOTE: code-writing is deliberately excluded (review round 3, F1). Its body
# (SKILL.md:108) says "The code-writing worker must not spawn reviewers or
# create nested fan-out" and (SKILL.md:110) "The parent schedules each
# required reviewer..." describes an EXTERNAL parent, not code-writing's own
# reader. code-writing is only ever coder-loaded (write-code.md:19 "Require
# the `coder` to load and follow the `code-writing` skill"; task-execution
# SKILL.md:51,57 lists it for the implementing worker) — never root-loaded.
# Keeping it here would re-inject the full spawn/handshake protocol into the
# coder mid-task, contradicting the worker note its agent.toml already
# carries. See MARKER_EXEMPT_SKILLS in tests/test_sync_to_codex.py for the
# matching test-guard exemption (its body still trips the generic
# orchestration-marker regex used by that test's completeness guard).
ORCHESTRATOR_SKILLS = frozenset({
    "feature-execution",
    "interview-planning",
    "methodology",
    "project-planning",
    "skill-tester",
    "task-decomposition",
    "task-execution",
    "tech-planning",
})
# Commands whose own body either (a) loads an ORCHESTRATOR_SKILLS skill directly
# for the invoking session to execute, or (b) itself instructs the invoking
# session to spawn an agent (e.g. advisor, setup-deploy's sysadmin delegation,
# write-code's coder delegation). Every other command is a non-spawning leaf.
ORCHESTRATOR_COMMANDS = frozenset({
    "advisor",
    "do-all-tasks",
    "do-task",
    "init-project-knowledge",
    "interview",
    "setup-deploy",
    "split-tasks",
    "tech-plan",
    "write-code",
})
SUPPORTED_MODELS = {"gpt-5.6-sol", "gpt-5.6-terra"}
SUPPORTED_EFFORTS = {"low", "medium", "high"}
MAX_CONFIGURED_THREADS = 6
FORBIDDEN_GENERATED_PATTERNS = (
    ("spawn_agent orchestration", re.compile(r"spawn_agent\s+orchestration", re.IGNORECASE)),
    ("Claude team directory", re.compile(r"~[/\\]\.claude[/\\]teams", re.IGNORECASE)),
    ("malformed Codex skill syntax", re.compile(r"Use\s+Codex\s+skill\s*:", re.IGNORECASE)),
)
NEGATIVE_TASK_LIFECYCLE_PREFIX = re.compile(
    r"(?:\b(?:do not|never)\s+(?:use|call|invoke)\s*:?"
    r"|\b(?:forbidden|unsupported)\s*:)\s*`?\s*$",
    re.IGNORECASE,
)
FORBIDDEN_HOOK_PATTERNS = (
    re.compile(r"\bteam_name\b", re.IGNORECASE),
    re.compile(r"\bScheduleWakeup\b", re.IGNORECASE),
    re.compile(r"/loop\b", re.IGNORECASE),
    re.compile(r"shared\s+inbox|unread", re.IGNORECASE),
    re.compile(r"resume\s+automatically", re.IGNORECASE),
)


class SyncError(Exception):
    """Base error for safe, user-actionable sync failures."""

    exit_code = 2


class ConflictError(SyncError):
    """A generated target was edited independently."""

    exit_code = 3


@dataclass(frozen=True)
class Output:
    source: str
    target: Path
    adapter: str
    content: str | bytes


@dataclass(frozen=True)
class PlannedAction:
    action: str
    output: Output | None
    target: Path
    reason: str = ""


@dataclass(frozen=True)
class RuntimePolicy:
    runtime: dict[str, int | str]
    profiles: dict[str, dict[str, str]]


def content_bytes(content: str | bytes) -> bytes:
    return content.encode("utf-8") if isinstance(content, str) else content


def digest(content: str | bytes) -> str:
    return hashlib.sha256(content_bytes(content)).hexdigest()


def validate_slug(value: str, label: str) -> None:
    if not SLUG_RE.fullmatch(value):
        raise SyncError(f"invalid {label} slug: {value!r}")


def relative_inside(path: Path, root: Path) -> Path:
    try:
        return path.resolve().relative_to(root.resolve())
    except ValueError as exc:
        raise SyncError(f"path escapes project root: {path}") from exc


def reject_symlink(path: Path, root: Path) -> None:
    relative = relative_inside(path, root)
    current = root.resolve()
    for part in relative.parts:
        current /= part
        if current.is_symlink():
            raise SyncError(f"symlink source rejected: {path}")


def contains_secret(text: str) -> bool:
    return any(pattern.search(text) for pattern in SECRET_PATTERNS)


def scan_quoted_string(text: str, start: int) -> int:
    quote = text[start]
    delimiter = quote * 3 if text.startswith(quote * 3, start) else quote
    index = start + len(delimiter)
    while index < len(text):
        if text[index] == "\\":
            index += 2
            continue
        if text.startswith(delimiter, index):
            return index + len(delimiter)
        index += 1
    return len(text)


def find_balanced_call_end(text: str, opening: int) -> int:
    depth = 0
    index = opening
    while index < len(text):
        if text[index] in {"'", '"'}:
            index = scan_quoted_string(text, index)
            continue
        if text[index] == "(":
            depth += 1
        elif text[index] == ")":
            depth -= 1
            if depth == 0:
                return index + 1
        index += 1
    return len(text)


def find_named_calls(text: str) -> list[tuple[str, int, int]]:
    calls: list[tuple[str, int, int]] = []
    index = 0
    while index < len(text):
        if text[index] in {"'", '"'}:
            index = scan_quoted_string(text, index)
            continue
        if not (text[index].isalpha() or text[index] == "_"):
            index += 1
            continue
        end = index + 1
        while end < len(text) and (text[end].isalnum() or text[end] == "_"):
            end += 1
        name = text[index:end]
        opening = end
        while opening < len(text) and text[opening].isspace():
            opening += 1
        if name in {"Task", "spawn_agent"} and text[opening:opening + 1] == "(":
            calls.append((name, index, find_balanced_call_end(text, opening)))
        index = end
    return calls


def call_tokens(text: str) -> list[tuple[str, str]]:
    tokens: list[tuple[str, str]] = []
    index = 0
    while index < len(text):
        if text[index].isspace():
            index += 1
            continue
        if text[index] in {"'", '"'}:
            end = scan_quoted_string(text, index)
            width = 3 if text.startswith(text[index] * 3, index) else 1
            tokens.append(("string", text[index + width : end - width]))
            index = end
            continue
        if text[index].isalpha() or text[index] == "_":
            end = index + 1
            while end < len(text) and (
                text[end].isalnum() or text[end] in {"_", "-"}
            ):
                end += 1
            tokens.append(("identifier", text[index:end]))
            index = end
            continue
        tokens.append(("punctuation", text[index]))
        index += 1
    return tokens


def has_named_argument(tokens: list[tuple[str, str]], names: set[str]) -> bool:
    for index, token in enumerate(tokens[:-1]):
        if token[0] != "identifier" or token[1].lower() not in names:
            continue
        if tokens[index + 1] == ("punctuation", "=") or tokens[index + 1] == (
            "punctuation",
            ":",
        ):
            return True
    return False


def has_general_purpose_agent_type(tokens: list[tuple[str, str]]) -> bool:
    for index, token in enumerate(tokens[:-2]):
        if token[0] != "identifier" or token[1].lower() != "agent_type":
            continue
        if tokens[index + 1] not in {
            ("punctuation", "="),
            ("punctuation", ":"),
        }:
            continue
        value_type, value = tokens[index + 2]
        if value_type in {"identifier", "string"} and value.lower() == "general-purpose":
            return True
    return False


def operative_calls(text: str) -> list[tuple[str, str]]:
    calls: list[tuple[str, str]] = []
    suppressed_until = -1
    for name, start, end in find_named_calls(text):
        if start < suppressed_until:
            continue
        prefix = text[max(0, start - 200) : start]
        if NEGATIVE_TASK_LIFECYCLE_PREFIX.search(prefix):
            suppressed_until = end
            continue
        opening = text.find("(", start, end)
        calls.append((name, text[opening + 1 : max(opening + 1, end - 1)]))
    return calls


def contains_operative_claude_task_lifecycle(text: str) -> bool:
    for name, arguments in operative_calls(text):
        if name == "Task" and has_named_argument(
            call_tokens(arguments),
            {"subagent_type"},
        ):
            return True
    return False


def contains_unsupported_spawn_recipe(text: str) -> bool:
    for name, arguments in operative_calls(text):
        if name != "spawn_agent":
            continue
        tokens = call_tokens(arguments)
        if has_named_argument(tokens, {"subagent_type", "team_name"}):
            return True
        if has_general_purpose_agent_type(tokens):
            return True
    return False


def decoded_text_values(value: object) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        return [
            text
            for nested in value.values()
            for text in decoded_text_values(nested)
        ]
    if isinstance(value, list):
        return [text for nested in value for text in decoded_text_values(nested)]
    return []


def read_source_bytes(path: Path, root: Path) -> bytes:
    reject_symlink(path, root)
    raw = path.read_bytes()
    if contains_secret(raw.decode("utf-8", errors="ignore")):
        raise SyncError(f"secret-looking content rejected: {path}")
    return raw


def read_source(path: Path, root: Path) -> str:
    try:
        text = read_source_bytes(path, root).decode("utf-8")
    except UnicodeDecodeError as exc:
        raise SyncError(f"non-UTF-8 source rejected: {path}") from exc
    if contains_secret(text):
        raise SyncError(f"secret-looking content rejected: {path}")
    return text


def split_frontmatter(text: str) -> tuple[dict[str, str | list[str]], str]:
    """Parse the small YAML subset used by Claude agent and skill files."""
    lines = text.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return {}, text
    end = next((index for index, line in enumerate(lines[1:], 1) if line.strip() == "---"), None)
    if end is None:
        raise SyncError("unterminated YAML frontmatter")

    raw = [line.rstrip("\r\n") for line in lines[1:end]]
    metadata: dict[str, str | list[str]] = {}
    index = 0
    while index < len(raw):
        line = raw[index]
        if not line.strip():
            index += 1
            continue
        match = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if not match:
            index += 1
            continue
        key, value = match.group(1), match.group(2).strip()
        if value in {"|", ">"}:
            index += 1
            block: list[str] = []
            while index < len(raw) and (not raw[index].strip() or raw[index][0].isspace()):
                block.append(raw[index].strip())
                index += 1
            metadata[key] = "\n".join(block).strip()
            continue
        if not value:
            index += 1
            values: list[str] = []
            while index < len(raw):
                item = re.match(r"^\s+-\s+(.+)$", raw[index])
                if not item:
                    break
                values.append(item.group(1).strip().strip("'\""))
                index += 1
            metadata[key] = values
            continue
        metadata[key] = value.strip("'\"")
        index += 1
    return metadata, "".join(lines[end + 1 :]).lstrip("\r\n")


def metadata_list(value: str | list[str] | None) -> list[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [item.strip() for item in value if item.strip()]
    stripped = value.strip()
    if stripped.startswith("[") and stripped.endswith("]"):
        stripped = stripped[1:-1]
    return [item.strip().strip("'\"") for item in stripped.split(",") if item.strip()]


def markdown_header(source: str) -> str:
    return f"<!-- {GENERATED_MARKER} Source: {source}. -->\n"


def toml_string(value: str) -> str:
    """Return a single-line TOML basic string and avoid multiline injection."""
    replacements = {
        "\\": "\\\\",
        '"': '\\"',
        "\b": "\\b",
        "\t": "\\t",
        "\n": "\\n",
        "\f": "\\f",
        "\r": "\\r",
    }
    encoded = "".join(replacements.get(char, char) for char in value)
    return f'"{encoded}"'


def serialize_agent(fields: dict[str, str]) -> str:
    required = {"name", "description", "developer_instructions", "sandbox_mode"}
    allowed = required | {"model", "model_reasoning_effort"}
    if not required.issubset(fields) or set(fields) - allowed:
        raise SyncError(f"unexpected Codex agent fields: {sorted(set(fields) - allowed)}")
    content = "\n".join(f"{key} = {toml_string(value)}" for key, value in fields.items()) + "\n"
    parsed = tomllib.loads(content)
    if parsed != fields:
        raise SyncError("Codex agent TOML failed round-trip validation")
    return f"# {GENERATED_MARKER}\n{content}"


def validate_runtime_table(runtime: object) -> dict[str, int | str]:
    if not isinstance(runtime, dict):
        raise SyncError("Codex runtime policy requires a [runtime] table")
    if set(runtime) != {"max_threads", "max_depth", "default_fork_turns"}:
        raise SyncError("Codex runtime policy requires max_threads, max_depth, and default_fork_turns")
    max_threads = runtime.get("max_threads")
    max_depth = runtime.get("max_depth")
    default_fork_turns = runtime.get("default_fork_turns")
    if type(max_threads) is not int or not 1 <= max_threads <= MAX_CONFIGURED_THREADS:
        raise SyncError(
            f"Codex runtime max_threads must be an integer from 1 to {MAX_CONFIGURED_THREADS}"
        )
    if type(max_depth) is not int or max_depth != 1:
        raise SyncError("Codex runtime max_depth must be integer 1")
    if not isinstance(default_fork_turns, str) or default_fork_turns != "none":
        raise SyncError('Codex runtime default_fork_turns must be "none"')
    return {
        "max_threads": max_threads,
        "max_depth": max_depth,
        "default_fork_turns": default_fork_turns,
    }


def validate_profile_coverage(project: Path, profiles: object) -> dict[str, object]:
    if not isinstance(profiles, dict):
        raise SyncError("Codex runtime policy requires [profiles.<role>] tables")
    source_agents = {path.stem for path in (project / ".claude/agents").glob("*.md")}
    profile_names = set(profiles)
    missing = sorted(source_agents - profile_names)
    extra = sorted(profile_names - source_agents)
    if missing:
        raise SyncError(f"agent profile coverage missing: {', '.join(missing)}")
    if extra:
        raise SyncError(f"agent profile coverage has extra names: {', '.join(extra)}")
    return profiles


def normalize_agent_profile(name: str, profile: object) -> dict[str, str]:
    if not isinstance(profile, dict):
        raise SyncError(f"agent profile must be a table: {name}")
    if set(profile) != {"model", "effort", "source"}:
        raise SyncError(f"agent profile requires model, effort, and source: {name}")
    model, effort, source = profile.get("model"), profile.get("effort"), profile.get("source")
    if not isinstance(model, str) or model not in SUPPORTED_MODELS:
        raise SyncError(f"unsupported model profile for agent {name}: {model}")
    if not isinstance(effort, str) or effort not in SUPPORTED_EFFORTS:
        raise SyncError(f"unsupported reasoning effort for agent {name}: {effort}")
    expected_source = f".claude/agents/{name}.md"
    if not isinstance(source, str) or Path(source).as_posix() != expected_source:
        raise SyncError(f"agent profile source must be {expected_source}: {name}")
    return {"model": model, "effort": effort, "source": source}


def load_runtime_policy(project: Path) -> RuntimePolicy:
    path = project / POLICY_REL
    if not path.is_file():
        raise SyncError(f"Codex runtime policy missing: {path}")
    reject_symlink(path, project)
    try:
        data = tomllib.loads(read_source(path, project))
    except tomllib.TOMLDecodeError as exc:
        raise SyncError(f"invalid Codex runtime policy: {path}: {exc}") from exc
    runtime = validate_runtime_table(data.get("runtime"))
    profiles = validate_profile_coverage(project, data.get("profiles"))
    normalized = {
        name: normalize_agent_profile(name, profile)
        for name, profile in profiles.items()
    }
    return RuntimePolicy(runtime=runtime, profiles=normalized)


def codex_runtime_note() -> str:
    return (
        "## Codex runtime adapter\n\n"
        "- Read `.codex/runtime-contract.md` before delegating or supervising parallel work.\n"
        "- The native delegation shape is "
        "`spawn_agent({task_name, message, fork_turns, agent_type?, model?, "
        "reasoning_effort?})`. `task_name` is only a scheduling label and does not bind a "
        "custom role.\n"
        "- Runtime-managed/fixed roles pass `agent_type=\"<exact-role>\"` and "
        "omit `model` and `reasoning_effort`. A generic/custom/default selectable worker "
        "uses `agent_type=\"default\"` (or the runtime default) and may pass model/effort "
        "only when the active schema supports those selectors.\n"
        "- Use `fork_turns=\"none\"` by default. Pass only a small number of turns when the "
        "subtask genuinely needs recent conversation context. Use model/effort selectors only "
        "with `fork_turns=\"none\"` or a bounded recent-turn count and only after the active "
        "schema accepts those fields.\n"
        "- Supervise with `followup_task`, `send_message`, `wait_agent`, `list_agents`, and "
        "`interrupt_agent`. The parent owns state, checkpoints, aggregation, and conflicts.\n"
        "- Lifecycle approval and owner authority never replace a native Codex tool request: the "
        "needing agent requests the exact command and justification. Chat approval is never a "
        "substitute; never request a magic authorization phrase.\n"
        "- An ordinary low-risk coder or read-only reviewer uses one single-turn spawn with no "
        "authorization handshake and no filesystem receipt. Use the handshake only for "
        "privileged/high-risk, destructive, deploy, migration, secret-access, or high-risk "
        "lifecycle-gate-producing roles that support follow-up; the parent writes the receipt.\n"
        "- One generic role-bound fallback is allowed only after the native fixed-role spawn "
        "returns an explicit unsupported-model error. Missing or unverified advisory metadata "
        "never qualifies. Preserve the same canonical role source and same bounded envelope.\n"
        "- A successful selectable-worker spawn proves requested-selector acceptance, not an "
        "independent resolved-model trace. Record the requested selector and acceptance/failure; "
        "record a resolved trace only if the runtime exposes one.\n"
        "- Codex has no automatic cross-session agent memory. When relevant, the parent task "
        "envelope explicitly tells the child to read `.claude/agent-memory/{agent}/MEMORY.md` as "
        "read-only input; do not claim hidden persistence or shared memory.\n"
        "- After denied native permission, stop and return control; only new user instruction or a "
        "materially changed exact command/justification permits another native request. Automatic "
        "or goal-continuation turns must never reissue permission cards.\n"
        "- Do not promise background callbacks or shared team memory. Children must not create children.\n"
        "- Keep `.claude/**` as the editable source of truth. Read generated `.agents/**` and `.codex/**` "
        "for runtime discovery, but never edit it directly.\n"
        "- After changing `CLAUDE.md` or `.claude/**`, run "
        "`python .claude/shared/scripts/sync_to_codex.py --project . --apply --prune`.\n"
    )


def codex_worker_note() -> str:
    return (
        "## Codex runtime adapter (worker)\n\n"
        "- You run as a single-turn leaf worker in a fresh isolated context supplied by the "
        "parent. You never spawn, delegate to, or supervise other agents; the root parent owns "
        "all orchestration, shared state, aggregation, and conflict resolution. Do your one job, "
        "return your result or evidence, and stop.\n"
        "- On a blocker, make at most two reproduce or diagnose attempts; if the second attempt "
        "still fails, stop and return your result citing the unmet precondition.\n"
        "- `.claude/**` is the editable source of truth. You may read generated `.agents/**` and "
        "`.codex/**` for discovery, but never edit generated files directly.\n"
        "- Codex has no automatic cross-session agent memory. Treat any "
        "`.claude/agent-memory/{agent}/MEMORY.md` the parent task envelope points you to as "
        "read-only input; do not write it or assume a later worker inherits it.\n"
        "- If your task genuinely needs elevated or native permission (sandbox, deploy, secret "
        "access, destructive effect), request it through the native Codex tool with the exact "
        "command and justification. Chat approval is not a substitute, and never ask the user to "
        "type a magic authorization phrase.\n"
    )


def render_agents_md(project: Path) -> Output:
    source = project / "CLAUDE.md"
    text = read_source(source, project)
    text = text.replace(
        "Slash command (e.g. `/interview`, `/tech-plan`, `/do-task`) → load `.claude/commands/{name}.md`; the command spec decides what skill to spawn.",
        "Slash-command intent (e.g. `/interview`, `/tech-plan`, `/do-task`) → use `.agents/skills/source-command-{name}/SKILL.md`; that adapter selects the methodology skill.",
    )
    text = text.replace(
        "Dev-related message (feature request, bug report, code question, refactor) → load `.claude/team-lead.md` (root); team-lead applies its own classifier to pick the pipeline.",
        "Dev-related message (feature request, bug report, code question, refactor) → use the `team-lead` skill from `.agents/skills/team-lead/SKILL.md`.",
    )
    text = text.replace("Team Lead protocol → `.claude/team-lead.md`", "Team Lead runtime → `.agents/skills/team-lead/SKILL.md`")
    text = text.replace("Agent specs → `.claude/agents/{name}.md`", "Native Codex agents → `.codex/agents/{name}.toml`")
    text = text.replace("Skills (methodology, code-writing, reviews, etc.) → `.claude/skills/{name}/SKILL.md`", "Codex skill runtime → `.agents/skills/{name}/SKILL.md`; editable source → `.claude/skills/{name}/SKILL.md`")
    preamble = (
        f"<!-- {GENERATED_MARKER} Source: CLAUDE.md. -->\n"
        "# Dual-runtime policy\n\n"
        "`CLAUDE.md` and `.claude/**` are the editable source of truth. `AGENTS.md`, `.agents/**`, "
        "and managed `.codex/**` files are generated Codex runtime files. Never edit generated files directly. "
        "When instructions, agents, commands, skills, or Project Knowledge change, edit the "
        "Claude-side source and regenerate Codex. Commit source and generated changes together.\n\n"
        "Codex may use independent and parallel subagents, but the parent agent must coordinate "
        "them explicitly; do not assume Claude Agent Team shared state exists.\n\n"
    )
    content = preamble + text
    return Output("CLAUDE.md", project / "AGENTS.md", "project-instructions", content)


def render_team_lead(project: Path) -> Output:
    source = project / ".claude/team-lead.md"
    body = read_source(source, project)
    content = (
        "---\n"
        "name: team-lead\n"
        "description: Orchestrate development requests, classify scope, plan work, delegate to specialists, supervise reviews, and aggregate results. Use for feature requests, bugs, refactors, implementation, and spec-driven delivery.\n"
        "---\n\n"
        f"{markdown_header('.claude/team-lead.md')}"
        f"{codex_runtime_note()}\n\n{body}"
    )
    return Output(source.relative_to(project).as_posix(), project / ".agents/skills/team-lead/SKILL.md", "team-lead", content)


def render_consultant_base(project: Path) -> Output:
    source = project / ".claude/consultant-base.md"
    relative = source.relative_to(project).as_posix()
    content = markdown_header(relative) + read_source(source, project)
    return Output(relative, project / ".codex/consultant-base.md", "shared-agent-contract", content)


def render_skill_outputs(project: Path) -> list[Output]:
    source_root = project / ".claude/skills"
    outputs: list[Output] = []
    if not source_root.is_dir():
        return outputs
    seen_names: set[str] = set()
    for skill_dir in sorted(path for path in source_root.iterdir() if path.is_dir()):
        validate_slug(skill_dir.name, "skill directory")
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.is_file():
            raise SyncError(f"skill missing SKILL.md: {skill_dir}")
        metadata, _ = split_frontmatter(read_source(skill_file, project))
        name = metadata.get("name")
        description = metadata.get("description")
        if not isinstance(name, str) or not isinstance(description, str) or not name or not description:
            raise SyncError(f"skill frontmatter requires name and description: {skill_file}")
        validate_slug(name, "skill name")
        if name != skill_dir.name:
            raise SyncError(f"skill name must match directory: {skill_file}")
        if name in seen_names:
            raise SyncError(f"duplicate skill name: {name}")
        seen_names.add(name)

        for source in sorted(path for path in skill_dir.rglob("*") if path.is_file()):
            if "__pycache__" in source.parts or source.suffix in {".pyc", ".pyo"}:
                continue
            relative = source.relative_to(source_root)
            source_relative = source.relative_to(project).as_posix()
            raw = read_source_bytes(source, project)
            try:
                source_text = raw.decode("utf-8")
            except UnicodeDecodeError:
                # Binary skill assets round-trip fine here (standalone
                # `--apply` CLI) — the generate_codex_runtime: true merge in
                # sync_to_os.py is what can't take bytes; that CONSUMER
                # refuses early instead. See "Binary skill assets" in
                # work/codex-dual-runtime/decisions.md for the full rationale.
                outputs.append(Output(source_relative, project / ".agents/skills" / relative, "skill-asset", raw))
                continue
            if contains_secret(source_text):
                raise SyncError(f"secret-looking content rejected: {source}")
            text = source_text
            if source.name == "SKILL.md":
                metadata, body = split_frontmatter(text)
                frontmatter = (
                    "---\n"
                    f"name: {metadata['name']}\n"
                    f"description: |\n  {str(metadata['description']).replace(chr(10), chr(10) + '  ')}\n"
                    "---\n\n"
                )
                note = codex_runtime_note() if name in ORCHESTRATOR_SKILLS else codex_worker_note()
                text = frontmatter + markdown_header(source_relative) + note + "\n\n" + body
            elif source.suffix == ".md":
                text = markdown_header(source_relative) + text
            outputs.append(Output(source_relative, project / ".agents/skills" / relative, "skill", text))
    return outputs


def render_agent_outputs(project: Path, policy: RuntimePolicy) -> list[Output]:
    source_root = project / ".claude/agents"
    outputs: list[Output] = []
    if not source_root.is_dir():
        return outputs
    for source in sorted(source_root.glob("*.md")):
        metadata, body = split_frontmatter(read_source(source, project))
        name, description = metadata.get("name"), metadata.get("description")
        if not isinstance(name, str) or not isinstance(description, str) or not name or not description:
            raise SyncError(f"agent frontmatter requires name and description: {source}")
        validate_slug(name, "agent name")
        if name != source.stem:
            raise SyncError(
                f"agent frontmatter name mismatch for {source.name}: "
                f"expected {source.stem}, got {name}"
            )
        tools = {tool.lower() for tool in metadata_list(metadata.get("allowed-tools"))}
        sandbox_mode = "workspace-write" if tools & WRITE_TOOLS else "read-only"
        instructions = codex_worker_note() + "\n\n" + body.strip()
        skills = metadata_list(metadata.get("skills"))
        if skills:
            pointers = "\n".join(
                f"- Load `.agents/skills/{skill}/SKILL.md` before starting." for skill in skills
            )
            instructions += f"\n\n## Required methodology\n\n{pointers}"
        if "consultant-base.md" in instructions:
            instructions += "\n\nRead `.codex/consultant-base.md` before analysis and follow its complete base contract."
        fields = {
            "name": name,
            "description": description,
            "developer_instructions": instructions,
            "sandbox_mode": sandbox_mode,
            "model": policy.profiles[name]["model"],
            "model_reasoning_effort": policy.profiles[name]["effort"],
        }
        outputs.append(
            Output(
                source.relative_to(project).as_posix(),
                project / ".codex/agents" / f"{name}.toml",
                "agent",
                serialize_agent(fields),
            )
        )
    return outputs


def render_command_outputs(project: Path) -> list[Output]:
    source_root = project / ".claude/commands"
    outputs: list[Output] = []
    if not source_root.is_dir():
        return outputs
    for source in sorted(source_root.glob("*.md")):
        validate_slug(source.stem, "command")
        metadata, body = split_frontmatter(read_source(source, project))
        raw_description = metadata.get("description")
        description = str(raw_description).splitlines()[0].strip() if raw_description else f"Run the {source.stem} workflow."
        raw_command = metadata.get("command")
        if raw_command is not None and (not isinstance(raw_command, str) or not raw_command.strip()):
            raise SyncError(f"command entrypoint must be a non-empty string: {source}")
        entrypoint = ""
        if isinstance(raw_command, str):
            if "\n" in raw_command or "`" in raw_command:
                raise SyncError(f"command entrypoint must be a safe single line: {source}")
            entrypoint = (
                "## Executable entrypoint\n\n"
                f"Executable entrypoint: `{raw_command}`\n\n"
                "Append user-supplied arguments to this entrypoint unchanged and pass through their "
                "ordering and values. Do not translate the command into tool-call syntax.\n\n"
            )
        slug = f"source-command-{source.stem}"
        validate_slug(slug, "command skill")
        source_relative = source.relative_to(project).as_posix()
        note = codex_runtime_note() if source.stem in ORCHESTRATOR_COMMANDS else codex_worker_note()
        content = (
            "---\n"
            f"name: {slug}\n"
            "description: |\n"
            f"  Codex adapter for the Claude `/{source.stem}` command. {description}\n"
            "  Use when the user invokes that command or asks for the equivalent workflow.\n"
            "---\n\n"
            f"{markdown_header(source_relative)}"
            f"{note}\n\n"
            f"# Command workflow: /{source.stem}\n\n"
            "Treat Claude-only command syntax as workflow intent and use the available Codex tools.\n\n"
            f"{entrypoint}"
            f"{body}"
        )
        outputs.append(
            Output(
                source_relative,
                project / ".agents/skills" / slug / "SKILL.md",
                "command-skill",
                content,
            )
        )
    return outputs


def render_codex_config(project: Path, policy: RuntimePolicy) -> Output:
    content = (
        f"# {GENERATED_MARKER}\n"
        "# The root orchestrator owns review waves and shared state.\n"
        "[agents]\n"
        f"max_threads = {policy.runtime['max_threads']}\n"
        f"max_depth = {policy.runtime['max_depth']}\n"
    )
    tomllib.loads(content)
    return Output(".claude/team-lead.md", project / ".codex/config.toml", "codex-config", content)


def render_runtime_contract(project: Path) -> Output:
    source = project / CONTRACT_REL
    if not source.is_file():
        raise SyncError(f"Codex runtime contract missing: {source}")
    content = markdown_header(CONTRACT_REL.as_posix()) + read_source(source, project)
    return Output(CONTRACT_REL.as_posix(), project / ".codex/runtime-contract.md", "runtime-contract", content)


def render_privileged_roles(project: Path) -> Output:
    source = project / PRIVILEGED_ROLES_REL
    if not source.is_file():
        raise SyncError(f"Codex privileged-roles doc missing: {source}")
    content = markdown_header(PRIVILEGED_ROLES_REL.as_posix()) + read_source(source, project)
    return Output(PRIVILEGED_ROLES_REL.as_posix(), project / ".codex/privileged-roles.md", "privileged-roles", content)


def render_checkpoint_hook_helper() -> str:
    return (
        "#!/usr/bin/env python3\n"
        '"""Surface durable feature checkpoints without scheduling or resuming work."""\n\n'
        "from __future__ import annotations\n\n"
        "import sys\n"
        "from pathlib import Path\n\n\n"
        "def main() -> int:\n"
        '    event = sys.argv[1] if len(sys.argv) > 1 else "session-start"\n'
        "    root = Path(__file__).resolve().parents[2]\n"
        '    print(f"Codex {event}: surfacing durable checkpoint context for the parent.")\n'
        '    for checkpoint in sorted(root.glob("work/*/logs/checkpoint.yml")):\n'
        '        print(checkpoint.relative_to(root).as_posix())\n'
        '    print("The parent must validate approvals and live runtime capability before any resume decision.")\n'
        "    return 0\n\n\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(main())\n"
    )


def render_hook_outputs(project: Path) -> list[Output]:
    source_root = project / ".claude/hooks"
    if not source_root.is_dir():
        return []
    outputs = [
        Output(
            ".claude/hooks",
            project / ".codex/hooks/checkpoint_context.py",
            "hook",
            render_checkpoint_hook_helper(),
        )
    ]
    command = (
        'python3 "$(git rev-parse --show-toplevel)/.codex/hooks/checkpoint_context.py" '
        "{event}"
    )
    command_windows = (
        "powershell.exe -NoProfile -NonInteractive -Command "
        '"$ErrorActionPreference = \'Stop\'; '
        "$root = (& git rev-parse --show-toplevel).Trim(); "
        "& python (Join-Path $root '.codex/hooks/checkpoint_context.py') '{event}'; "
        'exit $LASTEXITCODE"'
    )
    hooks = {
        "hooks": {
            "SessionStart": [
                {
                    "matcher": "startup|resume|clear",
                    "hooks": [{
                        "type": "command",
                        "command": command.format(event="session-start"),
                        "command_windows": command_windows.format(event="session-start"),
                        "statusMessage": "Checking resumable feature work",
                    }],
                },
                {
                    "matcher": "compact",
                    "hooks": [{
                        "type": "command",
                        "command": command.format(event="post-compaction"),
                        "command_windows": command_windows.format(event="post-compaction"),
                        "statusMessage": "Surfacing durable checkpoint context",
                    }],
                },
            ]
        }
    }
    content = json.dumps(hooks, ensure_ascii=False, indent=2) + "\n"
    outputs.append(Output(".claude/hooks", project / ".codex/hooks.json", "hooks-config", content))
    return outputs


def validate_generated_runtime(outputs: list[Output]) -> None:
    for output in outputs:
        if not isinstance(output.content, str):
            continue
        target = output.target.as_posix()
        lifecycle_text = output.content
        if target.endswith(".toml"):
            try:
                parsed = tomllib.loads(output.content)
            except tomllib.TOMLDecodeError as exc:
                raise SyncError(f"generated TOML is invalid: {output.target}: {exc}") from exc
            if "/.codex/agents/" in target:
                if parsed.get("model") not in SUPPORTED_MODELS:
                    raise SyncError(f"generated agent has no explicit supported model: {output.target}")
                if parsed.get("model_reasoning_effort") not in SUPPORTED_EFFORTS:
                    raise SyncError(f"generated agent has no explicit supported effort: {output.target}")
            lifecycle_text = "\n".join(decoded_text_values(parsed))

        if contains_operative_claude_task_lifecycle(lifecycle_text):
            raise SyncError(
                f"generated runtime contains operative Claude-only Task lifecycle: {output.target}"
            )
        if target.endswith("/.codex/runtime-contract.md") or target.endswith("/.codex/privileged-roles.md"):
            continue
        for label, pattern in FORBIDDEN_GENERATED_PATTERNS:
            if pattern.search(lifecycle_text):
                raise SyncError(f"generated runtime contains forbidden {label}: {output.target}")
        if contains_unsupported_spawn_recipe(lifecycle_text):
            raise SyncError(f"generated runtime contains unsupported spawn recipe: {output.target}")
        if "/.codex/hooks/" in target:
            for pattern in FORBIDDEN_HOOK_PATTERNS:
                if pattern.search(output.content):
                    raise SyncError(f"generated hook contains unsupported runtime assumption: {output.target}")


def build_outputs(project: Path) -> list[Output]:
    required = [project / "CLAUDE.md", project / ".claude/team-lead.md", project / ".claude/consultant-base.md"]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise SyncError(f"required sources missing: {', '.join(missing)}")
    policy = load_runtime_policy(project)
    outputs = [
        render_agents_md(project),
        render_team_lead(project),
        render_consultant_base(project),
        render_codex_config(project, policy),
        render_runtime_contract(project),
        render_privileged_roles(project),
    ]
    outputs.extend(render_skill_outputs(project))
    outputs.extend(render_agent_outputs(project, policy))
    outputs.extend(render_command_outputs(project))
    outputs.extend(render_hook_outputs(project))
    targets = [str(output.target.relative_to(project)) for output in outputs]
    if len(targets) != len(set(targets)):
        raise SyncError("two sources generate the same Codex target")
    for output in outputs:
        relative = relative_inside(output.target, project)
        if relative != Path("AGENTS.md") and relative.parts[:1] not in ((".codex",), (".agents",)):
            raise SyncError(f"generated target outside allowlist: {output.target}")
        if isinstance(output.content, str) and contains_secret(output.content):
            raise SyncError(f"secret-looking generated content rejected: {output.target}")
    validate_generated_runtime(outputs)
    return outputs


def validate_manifest_target(relative: str) -> None:
    posix = PurePosixPath(relative)
    windows = PureWindowsPath(relative)
    canonical = posix.as_posix()
    codex_exact_targets = {
        ".codex/config.toml",
        ".codex/consultant-base.md",
        ".codex/runtime-contract.md",
        ".codex/privileged-roles.md",
        ".codex/hooks.json",
        ".codex/hooks/checkpoint_context.py",
        ".codex/hooks/SessionStart.sh",
        ".codex/hooks/post-compact-restore.sh",
    }
    codex_agent_target = (
        len(posix.parts) == 3
        and posix.parts[:2] == (".codex", "agents")
        and posix.suffix == ".toml"
    )
    agents_skill_target = (
        len(posix.parts) >= 4
        and posix.parts[:2] == (".agents", "skills")
        and bool(SLUG_RE.fullmatch(posix.parts[2]))
    )
    managed = (
        relative == "AGENTS.md"
        or agents_skill_target
        or relative in codex_exact_targets
        or codex_agent_target
    )
    if (
        not relative
        or "\\" in relative
        or posix.is_absolute()
        or windows.is_absolute()
        or canonical != relative
        or ".." in posix.parts
        or not managed
    ):
        raise SyncError(f"manifest output target is not managed: {relative!r}")


def manifest_entry_matches_target(relative: str, source: str, adapter: str) -> bool:
    target = PurePosixPath(relative)
    if relative == "AGENTS.md":
        return source == "CLAUDE.md" and adapter == "project-instructions"
    if relative == ".agents/skills/team-lead/SKILL.md":
        return source == ".claude/team-lead.md" and adapter == "team-lead"
    if target.parts[:2] == (".agents", "skills"):
        source_path = PurePosixPath(source)
        if target.parts[2].startswith("source-command-"):
            command = target.parts[2].removeprefix("source-command-")
            return (
                target.parts[3:] == ("SKILL.md",)
                and source == f".claude/commands/{command}.md"
                and adapter == "command-skill"
            )
        expected_source = PurePosixPath(".claude", "skills", *target.parts[2:])
        return source_path == expected_source and adapter in {"skill", "skill-asset"}
    if target.parts[:2] == (".codex", "agents"):
        expected_source = f".claude/agents/{target.stem}.md"
        return source == expected_source and adapter == "agent"
    expected = {
        ".codex/config.toml": (".claude/team-lead.md", "codex-config"),
        ".codex/consultant-base.md": (
            ".claude/consultant-base.md",
            "shared-agent-contract",
        ),
        ".codex/runtime-contract.md": (
            ".claude/codex/runtime-contract.md",
            "runtime-contract",
        ),
        ".codex/privileged-roles.md": (
            ".claude/codex/privileged-roles.md",
            "privileged-roles",
        ),
        ".codex/hooks.json": (".claude/hooks", "hooks-config"),
        ".codex/hooks/checkpoint_context.py": (".claude/hooks", "hook"),
        ".codex/hooks/SessionStart.sh": (".claude/hooks/SessionStart.sh", "hook"),
        ".codex/hooks/post-compact-restore.sh": (
            ".claude/hooks/post-compact-restore.sh",
            "hook",
        ),
    }
    return expected.get(relative) == (source, adapter)


def validate_manifest_entry(relative: str, entry: object) -> None:
    validate_manifest_target(relative)
    required = {"source", "adapter", "source_sha256", "output_sha256"}
    if not isinstance(entry, dict) or set(entry) != required:
        raise SyncError(f"invalid manifest output entry: {relative}")
    if not isinstance(entry["source"], str) or not entry["source"]:
        raise SyncError(f"invalid manifest output entry source: {relative}")
    if not isinstance(entry["adapter"], str) or not entry["adapter"]:
        raise SyncError(f"invalid manifest output entry adapter: {relative}")
    if not manifest_entry_matches_target(relative, entry["source"], entry["adapter"]):
        raise SyncError(f"manifest output target is not managed: {relative!r}")
    for field in ("source_sha256", "output_sha256"):
        value = entry[field]
        if not isinstance(value, str) or not SHA256_RE.fullmatch(value):
            raise SyncError(f"invalid manifest output entry {field}: {relative}")


def load_manifest(project: Path) -> dict:
    path = project / MANIFEST_REL
    if not path.exists():
        return {
            "version": VERSION,
            "generator": MANIFEST_GENERATOR,
            "outputs": {},
        }
    reject_symlink(path, project)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise SyncError(f"invalid sync manifest: {path}") from exc
    if not isinstance(data, dict) or set(data) != {"version", "generator", "outputs"}:
        raise SyncError(f"invalid sync manifest schema: {path}")
    if data["version"] != VERSION:
        raise SyncError(f"unsupported sync manifest version: {data['version']!r}")
    if data["generator"] != MANIFEST_GENERATOR:
        raise SyncError(f"unexpected sync manifest generator: {data['generator']!r}")
    if not isinstance(data["outputs"], dict):
        raise SyncError(f"invalid outputs map in sync manifest: {path}")
    for relative, entry in data["outputs"].items():
        if not isinstance(relative, str):
            raise SyncError("manifest output key must be a string")
        validate_manifest_entry(relative, entry)
    return data


def plan_desired_actions(
    project: Path,
    desired: dict[str, Output],
    previous: dict,
    force: bool,
) -> list[PlannedAction]:
    actions: list[PlannedAction] = []
    for relative, output in sorted(desired.items()):
        target = output.target
        if not target.exists():
            actions.append(PlannedAction("create", output, target))
            continue
        reject_symlink(target, project)
        current = target.read_bytes()
        if current == content_bytes(output.content):
            actions.append(PlannedAction("unchanged", output, target))
            continue
        previous_hash = previous.get(relative, {}).get("output_sha256")
        if not force and (not previous_hash or digest(current) != previous_hash):
            actions.append(PlannedAction("conflict", output, target, "generated target was edited or is unmanaged"))
        else:
            actions.append(PlannedAction("update", output, target))
    return actions


def plan_stale_actions(
    project: Path,
    desired: dict[str, Output],
    previous: dict,
    prune: bool,
    force: bool,
) -> list[PlannedAction]:
    actions: list[PlannedAction] = []
    for relative, entry in sorted(previous.items()):
        if relative in desired:
            continue
        target = project / Path(relative)
        if not target.exists():
            continue
        reject_symlink(target, project)
        current_hash = digest(target.read_bytes())
        if current_hash != entry.get("output_sha256"):
            if force and prune:
                actions.append(
                    PlannedAction(
                        "delete",
                        None,
                        target,
                        "forced prune of edited stale generated target",
                    )
                )
            else:
                actions.append(
                    PlannedAction(
                        "conflict",
                        None,
                        target,
                        "stale generated target was edited",
                    )
                )
        elif prune:
            actions.append(PlannedAction("delete", None, target, "source removed"))
        else:
            actions.append(PlannedAction("stale", None, target, "source removed; rerun with --prune"))
    return actions


def plan_actions(
    project: Path,
    outputs: list[Output],
    prune: bool,
    force: bool,
) -> list[PlannedAction]:
    previous = load_manifest(project).get("outputs", {})
    desired = {
        str(output.target.relative_to(project)).replace("\\", "/"): output
        for output in outputs
    }
    return plan_desired_actions(project, desired, previous, force) + plan_stale_actions(
        project,
        desired,
        previous,
        prune,
        force,
    )


def atomic_write(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(content_bytes(content))
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, path)
    finally:
        temporary = Path(temporary_name)
        if temporary.exists():
            temporary.unlink()


def process_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def stale_lock(lock: Path) -> bool:
    try:
        raw = lock.read_text(encoding="utf-8").strip()
        pid = int(raw)
    except (OSError, UnicodeDecodeError, ValueError):
        return True
    return pid == os.getpid() or not process_alive(pid)


def acquire_lock(project: Path) -> Path:
    lock = project / LOCK_REL
    lock.parent.mkdir(parents=True, exist_ok=True)
    reject_symlink(lock.parent, project)
    for attempt in range(2):
        try:
            descriptor = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            break
        except FileExistsError as exc:
            if attempt == 0 and stale_lock(lock):
                lock.unlink()
                continue
            raise SyncError(f"another Codex sync may be running: {lock}") from exc
    else:  # pragma: no cover - loop either breaks or raises
        raise SyncError(f"could not acquire Codex sync lock: {lock}")
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(str(os.getpid()))
    return lock


def write_manifest(project: Path, outputs: list[Output]) -> None:
    entries = {}
    for output in sorted(outputs, key=lambda item: str(item.target)):
        relative = str(output.target.relative_to(project)).replace("\\", "/")
        source_path = project / output.source
        source_content = read_source_bytes(source_path, project) if source_path.is_file() else b""
        entries[relative] = {
            "source": output.source.replace("\\", "/"),
            "adapter": output.adapter,
            "source_sha256": digest(source_content),
            "output_sha256": digest(output.content),
        }
    manifest = {
        "version": VERSION,
        "generator": MANIFEST_GENERATOR,
        "outputs": entries,
    }
    atomic_write(project / MANIFEST_REL, json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n")


def _reconcile_manifest_to_disk(project: Path, outputs: list[Output], previous: dict) -> None:
    """Rebuild MANIFEST_REL from what is ACTUALLY on disk right now (F11 fix).

    Recovery path for a partial apply_actions() failure: the write loop below
    may die partway through (disk full, permission error, process killed),
    leaving some targets already rewritten to their NEW content while the
    manifest still holds the OLD pre-run hashes (write_manifest() only runs
    once, after the loop fully completes). On the next plan_actions() call,
    that stale manifest makes a file THIS SAME crashed run already rewrote
    look like it was "independently edited" (on-disk hash != manifest hash)
    — a phantom conflict that then demands --force, even though no human
    touched anything.

    Fix: after any exception during apply, re-derive every entry from the
    union of previously-tracked keys and newly-desired keys by hashing each
    target's REAL current bytes (not the previous manifest's hash, not the
    newly-desired-but-maybe-unwritten content). A target that no longer
    exists (successfully deleted before the crash) is dropped. A target
    still pending delete (crash happened before its turn) keeps its
    previous metadata with a refreshed hash, so the next run's
    plan_stale_actions() still sees it as owned-but-undesired and re-queues
    the delete — it is not silently orphaned from manifest tracking.
    """
    desired_by_key: dict[str, Output] = {
        str(output.target.relative_to(project)).replace("\\", "/"): output
        for output in outputs
    }
    entries: dict[str, dict] = {}
    for key in sorted(set(desired_by_key) | set(previous)):
        target = project / Path(key)
        if not target.exists():
            continue  # deleted (or never created) — must not appear in the manifest
        entries[key] = _reconciled_entry(project, target, desired_by_key.get(key), previous.get(key, {}))
    manifest = {"version": VERSION, "generator": MANIFEST_GENERATOR, "outputs": entries}
    atomic_write(project / MANIFEST_REL, json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n")


def _reconciled_entry(project: Path, target: Path, output: Output | None, previous_entry: dict) -> dict:
    """One manifest entry, hashed from `target`'s REAL current bytes.

    Auditor M1: sibling planners (plan_desired_actions/plan_stale_actions)
    both guard their target.read_bytes() with reject_symlink() — this
    recovery path must too. A SyncError raised here degrades correctly: the
    caller's best-effort except (apply_actions()) swallows it and re-raises
    the ORIGINAL crash exception.
    """
    reject_symlink(target, project)
    current_hash = digest(target.read_bytes())
    if output is None:
        return {**previous_entry, "output_sha256": current_hash}
    source_path = project / output.source
    source_content = read_source_bytes(source_path, project) if source_path.is_file() else b""
    return {
        "source": output.source.replace("\\", "/"),
        "adapter": output.adapter,
        "source_sha256": digest(source_content),
        "output_sha256": current_hash,
    }


def apply_actions(project: Path, outputs: list[Output], actions: list[PlannedAction]) -> None:
    stale = [action for action in actions if action.action == "stale"]
    if stale:
        paths = ", ".join(str(action.target.relative_to(project)) for action in stale)
        raise SyncError(
            "stale managed outputs require pruning before apply; "
            f"rerun with --apply --prune: {paths}"
        )
    conflicts = [action for action in actions if action.action == "conflict"]
    if conflicts:
        paths = ", ".join(str(action.target.relative_to(project)) for action in conflicts)
        raise ConflictError(f"refusing to overwrite independently edited targets: {paths}")
    lock = acquire_lock(project)
    try:
        try:
            for action in actions:
                if action.action in {"create", "update"}:
                    assert action.output is not None
                    atomic_write(action.target, action.output.content)
                elif action.action == "delete":
                    action.target.unlink()
                    parent = action.target.parent
                    while parent != project and parent != project / ".codex" and parent.exists():
                        try:
                            parent.rmdir()
                        except OSError:
                            break
                        parent = parent.parent
            write_manifest(project, outputs)
        except BaseException:
            # F11 fix: a partial failure must not leave a stale manifest
            # behind — reconcile it to physical reality (best-effort; the
            # ORIGINAL exception always propagates regardless of whether
            # this recovery write itself succeeds).
            try:
                _reconcile_manifest_to_disk(project, outputs, load_manifest(project).get("outputs", {}))
            except Exception:
                pass
            raise
    finally:
        lock.unlink(missing_ok=True)


def report(project: Path, actions: list[PlannedAction]) -> None:
    counts: dict[str, int] = {}
    for action in actions:
        counts[action.action] = counts.get(action.action, 0) + 1
    summary = ", ".join(f"{key}={counts[key]}" for key in sorted(counts))
    print(f"sync-to-codex: {summary or 'no outputs'}")
    for action in actions:
        if action.action not in {"unchanged"}:
            suffix = f" ({action.reason})" if action.reason else ""
            print(f"  {action.action}: {action.target.relative_to(project)}{suffix}")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--apply", action="store_true", help="Write generated runtime files.")
    mode.add_argument("--check", action="store_true", help="Exit 1 when generated runtime has drift.")
    parser.add_argument("--project", type=Path, default=Path.cwd(), help="Project root. Default: current directory.")
    parser.add_argument("--prune", action="store_true", help="Delete stale manifest-owned outputs.")
    parser.add_argument("--force", action="store_true", help="Overwrite unmanaged or independently edited generated targets.")
    parser.add_argument("--quiet", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    project = args.project.expanduser().resolve()
    if not project.is_dir():
        print(f"error: project root not found: {project}", file=sys.stderr)
        return 2
    try:
        outputs = build_outputs(project)
        actions = plan_actions(project, outputs, prune=args.prune, force=args.force)
        if not args.quiet:
            report(project, actions)
        if args.apply:
            apply_actions(project, outputs, actions)
            if not args.quiet:
                print("Codex runtime generated successfully.")
            return 0
        drift = any(action.action not in {"unchanged"} for action in actions)
        if args.check and drift:
            return 1
        return 0
    except SyncError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return exc.exit_code


if __name__ == "__main__":
    raise SystemExit(main())
